name: main

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - main
  # schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron:  '30 5,17 * * *'
    
# on: push    # Default will running for every branch.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # This job will run on windows virtual machine
    runs-on: windows-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '3.16.4' # you can also specify exact version of flutter
    
    # Get flutter dependencies.
    - run: flutter clean
    - run: flutter pub get
    - run: flutter analyze
    
    # Build apk.
    - run: flutter build apk --release
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: main_release_app
        path: build/app/outputs/flutter-apk/app-release.apk
        # 
        